version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn        

      - run: yarn workspace gatsby-mdx test
      - run: yarn workspace babel-plugin-gather-exports test
      - run: yarn workspace babel-plugin-pluck-imports test
      - run: yarn workspace babel-plugin-pluck-exports test
      - run: yarn lint
